### PR TITLE
fix: typo & improve failed binaries error reporting

### LINKED ISSUE #7927: Typo in the vegavisor config
# Problem encountered|

There is a typo spotted by Ed on discord.

We have the following config in vegavisor run-config:

```toml
[autoInstall]
  enabled = true
  repositoryOwner = "vegaprotocol"
  repository = "vega"
  [autoInstall.assets]
    [autoInstall.assets.vega]
      assset_name = "vega-linux-amd64.zip"
      binary_name = "vega"
    # We use vega datanode subcommand to start data-node. See example below
    [autoInstall.assets.data_node]
      assset_name = "vega-linux-amd64.zip"
      binary_name = "vega"
```

There is a typo in word `assset_name` it has `3 s'` chars instead of 2.

- `assset_name` - this is now
- `asset_name` - this should be 

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

### PR DESCRIPTION
**Pull request by karlem**
Close #7927 

The following PR needs to be merged at the same time:

- https://github.com/vegaprotocol/vegacapsule/pull/388
- https://github.com/vegaprotocol/system-tests/pull/2005
- https://github.com/vegaprotocol/vega/pull/7930
- https://github.com/vegaprotocol/ansible/pull/512

### CODE REVIEW

**Review by jeremyletang — DISMISSED** [review]

**Review by daniel1302 — DISMISSED** [review]

**Review by daniel1302 — DISMISSED** [review]

**Comment by daniel1302** [comment]
I have triggered build with custom branches mentioned in the description:

-  https://jenkins.ops.vega.xyz/blue/organizations/jenkins/vega/detail/PR-7930/12/pipeline
- VISOR PUP and auto install tests: https://jenkins.ops.vega.xyz/job/common/job/visor-autoinstall-and-pup/658/

**Review by daniel1302 — APPROVED** [review]

**Review by jeremyletang — APPROVED** [review]
